/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: ["selector", '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        accent: "var(--color-accent)",
        "accent-deep": "var(--color-accent-deep)",
        "accent-tint": "var(--color-accent-tint)",
        "on-accent": "var(--color-on-accent)",
        canvas: "var(--color-canvas)",
        surface: "var(--color-surface)",
        "surface-raised": "var(--color-surface-raised)",
        "surface-sunken": "var(--color-surface-sunken)",
        hairline: "var(--color-hairline)",
        "hairline-strong": "var(--color-hairline-strong)",
        overlay: "var(--color-overlay)",
        ink: "var(--color-ink)",
        body: "var(--color-body)",
        mute: "var(--color-mute)",
        stone: "var(--color-stone)",
        faint: "var(--color-faint)",
        "on-fill": "var(--color-on-fill)",
        "verdict-aligned": "var(--color-verdict-aligned)",
        "verdict-aligned-tint": "var(--color-verdict-aligned-tint)",
        "verdict-partial": "var(--color-verdict-partial)",
        "verdict-partial-tint": "var(--color-verdict-partial-tint)",
        "verdict-misaligned": "var(--color-verdict-misaligned)",
        "verdict-misaligned-tint": "var(--color-verdict-misaligned-tint)",
        "verdict-unrelated": "var(--color-verdict-unrelated)",
        "verdict-unrelated-tint": "var(--color-verdict-unrelated-tint)",
        "code-bg": "var(--color-code-bg)",
        "code-gutter": "var(--color-code-gutter)",
        "code-line-no": "var(--color-code-line-no)",
        "code-plain": "var(--color-code-plain)",
        "code-comment": "var(--color-code-comment)",
        "code-keyword": "var(--color-code-keyword)",
        "code-string": "var(--color-code-string)",
        "code-number": "var(--color-code-number)",
        "code-function": "var(--color-code-function)",
        "code-operator": "var(--color-code-operator)",
        "code-punct": "var(--color-code-punct)",
        "code-evidence-bg": "var(--color-code-evidence-bg)",
      },
      spacing: {
        xxs: "var(--spacing-xxs)",
        xs: "var(--spacing-xs)",
        sm: "var(--spacing-sm)",
        md: "var(--spacing-md)",
        lg: "var(--spacing-lg)",
        xl: "var(--spacing-xl)",
        xxl: "var(--spacing-xxl)",
        xxxl: "var(--spacing-xxxl)",
        section: "var(--spacing-section)",
      },
      borderRadius: {
        none: "var(--rounded-none)",
        xs: "var(--rounded-xs)",
        sm: "var(--rounded-sm)",
        md: "var(--rounded-md)",
        lg: "var(--rounded-lg)",
        full: "var(--rounded-full)",
      },
      boxShadow: {
        pop: "var(--shadow-pop)",
      },
      fontFamily: {
        sans: ["Roboto", "Helvetica Neue", "Arial", "system-ui", "sans-serif"],
        mono: ["Fira Code", "JetBrains Mono", "SF Mono", "Consolas", "monospace"],
      },
      fontSize: {
        "title-xl": ["32px", { lineHeight: "1.2", letterSpacing: "-0.6px" }],
        "title-lg": ["24px", { lineHeight: "1.25", letterSpacing: "-0.4px" }],
        "title-md": ["20px", { lineHeight: "1.3", letterSpacing: "-0.2px" }],
        "title-sm": ["16px", { lineHeight: "1.4", letterSpacing: "0" }],
        "body-lg": ["16px", { lineHeight: "1.6", letterSpacing: "0" }],
        "body-md": ["14px", { lineHeight: "1.55", letterSpacing: "0" }],
        "body-sm": ["13px", { lineHeight: "1.5", letterSpacing: "0" }],
        "label-md": ["13px", { lineHeight: "1.4", letterSpacing: "0" }],
        "label-sm": ["12px", { lineHeight: "1.35", letterSpacing: "0" }],
        caption: ["12px", { lineHeight: "1.4", letterSpacing: "0" }],
        "stat-xl": ["34px", { lineHeight: "1.0", letterSpacing: "-0.5px" }],
        "mono-eyebrow": ["11px", { lineHeight: "1.2", letterSpacing: "0.9px" }],
        "mono-id": ["12px", { lineHeight: "1.3", letterSpacing: "0.2px" }],
        "mono-code": ["13px", { lineHeight: "1.65", letterSpacing: "0" }],
        "mono-code-sm": ["12px", { lineHeight: "1.6", letterSpacing: "0" }],
      },
      transitionDuration: {
        fast: "120ms",
        base: "180ms",
        slow: "260ms",
      },
      keyframes: {
        "skeleton-pulse": { "0%, 100%": { opacity: "1" }, "50%": { opacity: "0.6" } },
        indeterminate: {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(300%)" },
        },
      },
      animation: {
        "skeleton-pulse": "skeleton-pulse 1.4s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
